# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 142e1db5ad1abf55ad5216ca86db9509a5379cde0d303fb0e771f7ee5a0dd811a9491eef0024c50c23481dff94b6595472e6046f77d50a3577fc72a63bca1b3b

test:
  secret_key_base: 85c31dd7019616c677c526e3b5f1b1e8c7aa8d9aa47302d701e3ab99537cf9e2880ce2c000dc90b91a07274360a279749eec084a299c636ed717f0faa6797fbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
